//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Knowledge> Knowledges { get; set; }
        public virtual DbSet<KnowledgeType> KnowledgeTypes { get; set; }
        public virtual DbSet<MeetingAgenda> MeetingAgendas { get; set; }
        public virtual DbSet<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual DbSet<MeetingFollowup> MeetingFollowups { get; set; }
        public virtual DbSet<MeetingOccurance> MeetingOccurances { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<QuestionCondition> QuestionConditions { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<SurveyAssignee> SurveyAssignees { get; set; }
        public virtual DbSet<SurveyAssignment> SurveyAssignments { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveySection> SurveySections { get; set; }
        public virtual DbSet<SurveySubmission> SurveySubmissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<QuestionTypeFormat> QuestionTypeFormats { get; set; }
    
        public virtual int GetSurveySubmitById(Nullable<long> surveyAssigneeId)
        {
            var surveyAssigneeIdParameter = surveyAssigneeId.HasValue ?
                new ObjectParameter("SurveyAssigneeId", surveyAssigneeId) :
                new ObjectParameter("SurveyAssigneeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSurveySubmitById", surveyAssigneeIdParameter);
        }
    }
}
