//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingAgenda
    {
        public long MeetingAgendaID { get; set; }
        public long MeetingID { get; set; }
        public int Version { get; set; }
        public string Title { get; set; }
        public int AssigneeID { get; set; }
        public string Comments { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IP { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
