//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOption
    {
        public long QuestionOptionID { get; set; }
        public long QuestionID { get; set; }
        public string Option { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IP { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
