//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionOptions = new HashSet<QuestionOption>();
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public long QuestionID { get; set; }
        public int CategoryID { get; set; }
        public int QuestionTypeID { get; set; }
        public string Name { get; set; }
        public bool IsRequired { get; set; }
        public string Hint { get; set; }
        public int Length { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IP { get; set; }
        public Nullable<bool> IsNotApplicableOption { get; set; }
        public Nullable<bool> IsDontKnowOption { get; set; }
        public Nullable<bool> IsAdvanced { get; set; }
        public string Comments { get; set; }
        public bool IsUsedInSurvey { get; set; }
        public Nullable<bool> DoRecordGPS { get; set; }
        public Nullable<int> FormatID { get; set; }
        public string Unit { get; set; }
        public string CascadeDropdownMarkup { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}
