//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySubmission
    {
        public long SurveySubmissionID { get; set; }
        public long SurveyAssigneeID { get; set; }
        public long SurveyID { get; set; }
        public int AssigneeID { get; set; }
        public long QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<long> QuestionOptionID { get; set; }
        public string QuestionOption { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IP { get; set; }
        public Nullable<int> SyncStatus { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Comment { get; set; }
    }
}
