//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAssignee
    {
        public long SurveyAssigneeID { get; set; }
        public Nullable<long> SurveyAssignmentID { get; set; }
        public long SurveyID { get; set; }
        public int AssigneeID { get; set; }
        public int RoleID { get; set; }
        public bool IsOptional { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IP { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
