//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string LoginId { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public int GenderId { get; set; }
        public string DateOfBirth { get; set; }
        public string CNIC { get; set; }
        public int EducationId { get; set; }
        public string Education { get; set; }
        public int ProfessionId { get; set; }
        public string Profession { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public int DesignationSiblingId { get; set; }
        public string DesignationSibling { get; set; }
        public int DepartmentId { get; set; }
        public string Department { get; set; }
        public int IsActive { get; set; }
        public int UserRole { get; set; }
        public string UserRoleName { get; set; }
    }
}
