using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("ConditionGetAll")]
        public async Task<string> ConditionGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    IConditionBLL bll = IOC.Resolve<IConditionBLL>();
                    IEnumerable<ConditionDTO> entities = await bll.GetAllAsync();
                    return _serializer.Serialize(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}