using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("KnowledgeTypeGetDropDownList")]
        public async Task<string> KnowledgeTypeGetDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();
                    int? defaultKey = ((JValue)jObject["defaultKey"]).Value<int?>();
                    string defaultValue = ((JValue)jObject["defaultValue"]).Value<string>();

                    IKnowledgeTypeBLL bll = IOC.Resolve<IKnowledgeTypeBLL>();
                    IEnumerable<KeyValuePair<int, string>> entities = await bll.GetAllKeyValuePairAsync(isActive, defaultKey, defaultValue);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}