using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("KnowledgeGetAll")]
        public async Task<string> KnowledgeGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    var knowledgeTypeID = ((JValue)jObject["KnowledgeTypeID"]).Value<int>();

                    IKnowledgeBLL bll = IOC.Resolve<IKnowledgeBLL>();
                    IEnumerable<KnowledgeDTO> entities = await bll.GetAllAsync(knowledgeTypeID);
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("KnowledgeInsertOrUpdate")]
        public async Task<string> KnowledgeInsertOrUpdate(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<KnowledgeDTO>(_postedJson);

                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var bll = IOC.Resolve<IKnowledgeBLL>();
                    var id = await bll.InsertOrUpdateAsync(data);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("KnowledgeDelete")]
        public async Task<string> KnowledgeDelete(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long id = ((JValue)jObject["ID"]).Value<long>();

                    var bll = IOC.Resolve<IKnowledgeBLL>();
                    await bll.DeleteAsync(id);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("KnowledgeGetById")]
        public async Task<string> KnowledgeGetById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long knowledgeID = ((JValue)jObject["id"]).Value<long>();

                    var bll = IOC.Resolve<IKnowledgeBLL>();
                    await bll.GetByIdAsync(knowledgeID);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}