using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("MeetingGetAll")]
        public async Task<string> MeetingGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    var meetingOccuranceID = ((JValue)jObject["MeetingOccuranceID"]).Value<int>();

                    IMeetingBLL bll = IOC.Resolve<IMeetingBLL>();
                    IEnumerable<MeetingDTO> entities = await bll.GetAllAsync(meetingOccuranceID);
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("MeetingInsertOrUpdate")]
        public async Task<string> MeetingInsertOrUpdate(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<MeetingDTO>(_postedJson);

                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var bll = IOC.Resolve<IMeetingBLL>();
                    var id = await bll.InsertOrUpdateAsync(data);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("MeetingDelete")]
        public async Task<string> MeetingDelete(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long id = ((JValue)jObject["ID"]).Value<long>();

                    var bll = IOC.Resolve<IMeetingBLL>();
                    await bll.DeleteAsync(id);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}