using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;
using static Unity.Storage.RegistrationSet;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("QuestionGetDropDownList")]
        public async Task<string> QuestionGetDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();
                    long? defaultKey = ((JValue)jObject["defaultKey"]).Value<long?>();
                    string defaultValue = ((JValue)jObject["defaultValue"]).Value<string>();

                    IQuestionBLL bll = IOC.Resolve<IQuestionBLL>();
                    IEnumerable<KeyValuePair<long, string>> entities = await bll.GetAllKeyValuePairAsync(isActive, defaultKey, defaultValue);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
        
        [RequestDirectTo("QuestionGetAll")]    
        public async Task<string> QuestionsGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    var categoryID = ((JValue)jObject["categoryID"]).Value<int>();
                    var questionTypeID = ((JValue)jObject["questionTypeID"]).Value<int>();

                    IQuestionBLL bll = IOC.Resolve<IQuestionBLL>();
                    IEnumerable<QuestionDTO> entities = await bll.GetAllAsync(categoryID, questionTypeID);
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("QuestionInsertOrUpdate")]
        public async Task<string> QuestionInsertOrUpdate(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<QuestionDTO>(_postedJson);
                
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }   
                else
                {
                    var bll = IOC.Resolve<IQuestionBLL>();
                    var id = await bll.InsertOrUpdateAsync(data);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("QuestionDelete")]
        public async Task<string> DeleteQuestion(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long questionID = ((JValue)jObject["QuestionID"]).Value<long>();

                    var bll = IOC.Resolve<IQuestionBLL>();
                    await bll.DeleteAsync(questionID);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("QuestionGetById")]
        public async Task<string> QuestionGetById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long questionID = ((JValue)jObject["QuestionID"]).Value<long>();

                    var bll = IOC.Resolve<IQuestionBLL>();
                    var entity = await bll.GetByIdAsync(questionID);
                    return ServiceResponse.GetOKResponse(entity);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("QuestionGetAll2")]
        public async Task<string> QuestionsGetAll2(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();

                    IQuestionBLL bll = IOC.Resolve<IQuestionBLL>();
                    IEnumerable<QuestionDTO> entities = await bll.GetAllAsync(isActive);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("QuestionOptionGetDropDownList")]
        public async Task<string> QuestionOptionGetDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();
                    long? defaultKey = ((JValue)jObject["defaultKey"]).Value<long?>();
                    string defaultValue = ((JValue)jObject["defaultValue"]).Value<string>();
                    long questionID = ((JValue)jObject["questionID"]).Value<long>();

                    IQuestionOptionBLL bll = IOC.Resolve<IQuestionOptionBLL>();
                    IEnumerable<KeyValuePair<long, string>> entities = await bll.GetAllKeyValuePairAsync(isActive, defaultKey, defaultValue, questionID);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}