using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("SurveyAssignmentGetAll")]
        public async Task<string> SurveyAssignmentGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;

                    ISurveyAssignmentBLL bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    IEnumerable<SurveyAssignmentDTO> entities = await bll.GetAllAsync();
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("UserGetDropDownList")]
        public async Task<string> UserGetDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    //bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();
                    int? defaultKey = ((JValue)jObject["defaultKey"]).Value<int?>();
                    string defaultValue = ((JValue)jObject["defaultValue"]).Value<string>();

                    IUserBLL bll = IOC.Resolve<IUserBLL>();
                    IEnumerable<KeyValuePair<int, string>> entities = await bll.GetAllKeyValuePairAsync(defaultKey, defaultValue);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("GetAllUserDropDownList")]
        public async Task<string> GetAllUserDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;

                    IUserBLL bll = IOC.Resolve<IUserBLL>();
                    IEnumerable<UserDTO2> entities = await bll.GetAllUsersAsync();
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("GetSurveyDeploymentInitDataDTO")]
        public async Task<string> GetSurveyDeploymentInitDataDTO(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyId = ((JValue)jObject["serveyId"]).Value<long>();

                    var bll2 = IOC.Resolve<ISurveyAssignmentBLL>();
                    SurveyDeploymentInitDataDTO dto = await bll2.GetSurveyDeploymentInitDataDTOAsync(surveyId);

                    return ServiceResponse.GetOKResponse(dto);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyAssignmentInsertOrUpdate")]
        public async Task<string> SurveyAssignmentInsertOrUpdate(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<SurveyAssignmentDTO>(_postedJson);

                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    var id = await bll.InsertOrUpdateAsync(data);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyAssignmentDelete")]
        public async Task<string> SurveyAssignmentDelete(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long id = ((JValue)jObject["SurveyAssignmentID"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    await bll.DeleteAsync(id);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyAssignmentGetById")]
        public async Task<string> SurveyAssignmentGetById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyAssignmentId = ((JValue)jObject["SurveyAssignmentID"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    var data = await bll.GetByIdAsync(surveyAssignmentId);
                    return ServiceResponse.GetOKResponse(data);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveySubmitGetAll")]
        public async Task<string> SurveySubmitGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyId = Convert.ToInt64(HttpContext.Current.Request.QueryString["sid2"]);
                    ISurveyAssignmentBLL bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    IEnumerable<SurveyAssignmentDTO> entities = await bll.GetAllSubmitAsync(surveyId);
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveySubmitGetById")]
        public async Task<string> SurveySubmitGetById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyAssigneeId = ((JValue)jObject["SurveyAssigneeID"]).Value<long>();

                    ISurveyAssignmentBLL bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    SurveySubmitDTO data = await bll.GetSubmitByIdAsync(surveyAssigneeId);
                    return ServiceResponse.GetOKResponse(data);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveySubmitDelete")]
        public async Task<string> SurveySubmitDelete(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyAssigneeId = ((JValue)jObject["SurveyAssigneeID"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    await bll.SubmitDeleteAsync(surveyAssigneeId);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("GetDeployAssignees")]
        public async Task<string> GetDeployAssignees(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    long surveyId = Convert.ToInt64(HttpContext.Current.Request.QueryString["surveyId"]);
                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    var data = await bll.GetDeployAssigneesAsync(surveyId);
                    return _serializer.Serialize(data);
                }
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("DeploySurveySaveSingle")]
        public async Task<string> DeploySurveySaveSingle(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyId = ((JValue)jObject["SurveyID"]).Value<long>();
                    int userId = ((JValue)jObject["UserID"]).Value<int>();
                    int roleId = ((JValue)jObject["RoleID"]).Value<int>();

                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    var id = await bll.SaveSingleAssigneeAsync(surveyId, userId, roleId);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("DeploySurveyDeleteSingle")]
        public async Task<string> DeploySurveyDeleteSingle(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyAssigneeId = ((JValue)jObject["SurveyAssigneeID"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyAssignmentBLL>();
                    await bll.DeleteSingleAssigneeAsync(surveyAssigneeId);
                    return ServiceResponse.GetOKResponse(null);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}