using System;
using System.Collections.Generic;
using System.Web;
using MAS.InversionOfControl;
using MAS.Utility;
using MAS.BusinessLogicLayer.Contract;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MAS.Exceptions;
using MAS.Web.App_Start;
using MAS.DataTransferObject;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;

namespace MAS.Web
{
    public partial class Service : System.Web.UI.Page
    {
        [RequestDirectTo("SurveyGetDropDownList")]
        public async Task<string> SurveyGetDropDownList(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    bool? isActive = ((JValue)jObject["isActive"]).Value<bool?>();
                    int? defaultKey = ((JValue)jObject["defaultKey"]).Value<int?>();
                    string defaultValue = ((JValue)jObject["defaultValue"]).Value<string>();

                    ISurveyBLL bll = IOC.Resolve<ISurveyBLL>();
                    IEnumerable<KeyValuePair<long, string>> entities = await bll.GetAllKeyValuePairAsync(isActive, defaultKey, defaultValue);
                    return ServiceResponse.GetOKResponse(entities);
                }
            }
            catch (DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyGetAll")]
        public async Task<string> SurveyGetAll(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    //var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    //var categoryID = ((JValue)jObject["categoryID"]).Value<int>();
                    //var questionTypeID = ((JValue)jObject["questionTypeID"]).Value<int>();
                    int categoryId = Convert.ToInt32(HttpContext.Current.Request.QueryString["c"]);
                    var token = HttpContext.Current.Request.Cookies["Token"].Value;
                    UserInformationDTO dto = JsonConvert.DeserializeObject<UserInformationDTO>(token);
                    ISurveyBLL bll = IOC.Resolve<ISurveyBLL>();
                    IEnumerable<SurveyDTO> entities = await bll.GetAllAsync(dto.RoleID, dto.UserID,categoryId);
                    return _serializer.Serialize(entities);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyInsertOrUpdate")]
        public async Task<string> SurveyInsertOrUpdate(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<Survey2DTO>(_postedJson);

                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var bll = IOC.Resolve<ISurveyBLL>();
                    var id = await bll.InsertOrUpdateAsync(data);
                    return ServiceResponse.GetOKResponse(id);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyGetById")]
        public async Task<string> SurveyGetById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyID = ((JValue)jObject["SurveyID"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyBLL>();
                    var entity = await bll.GetByIdAsync(surveyID);
                    return ServiceResponse.GetOKResponse(entity);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("DeleteSurveyById")]
        public async Task<string> DeleteSurveyById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyID = ((JValue)jObject["Id"]).Value<long>();

                    var bll = IOC.Resolve<ISurveyBLL>();
                    await bll.DeleteByIDAsync(surveyID);
                    return ServiceResponse.SuccessResponse;
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("UpdateSurveyAnswer")]
        public async Task<string> UpdateSurveyAnswer(HttpContext context)
        {
            try
            {
                var data = JsonConvert.DeserializeObject<SurveySubmissionDTO>(_postedJson);

                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var bll = IOC.Resolve<ISurveyBLL>();
                    await bll.UpdateSurveyAnswerAsync(data);
                    return ServiceResponse.SuccessResponse;
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }

        [RequestDirectTo("SurveyReportById")]
        public async Task<string> SurveyReportById(HttpContext context)
        {
            try
            {
                if (!StrongTypeSession.UserAutoGeneratedId.HasValue)
                {
                    return ServiceResponse.AuthenticationErrorResponse;
                }
                else
                {
                    var jObject = JsonConvert.DeserializeObject(_postedJson) as JObject;
                    long surveyID = ((JValue)jObject["SurveyID"]).Value<long>();

                    var connectionString = ConfigurationManager.ConnectionStrings["MASConnectionString"].ToString();
                    var parameters = new SqlParameter[]
                        {
                                    new SqlParameter("@SurveyID", surveyID){SqlDbType = SqlDbType.BigInt},
                        };
                    string query = "SP_SurveyReport";
                    var dta = SqlHelper.GetDataSetFromSP(connectionString, query, parameters);
                    var json = JSONSerializer.ToJson(dta);
                    return ServiceResponse.GetOKResponse(json);
                }
            }
            catch (MAS.Exceptions.DALException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.DAL, ex.Message, null);
            }
            catch (MAS.Exceptions.BLLException ex)
            {
                return ServiceResponse.GetErrorResponse(ErrorClass.BLL, ex.Message, null);
            }
            catch (Exception ex)
            {
                _logger.Error("Error", ex);
                return ServiceResponse.UnExpectedErrorResponse;
            }
        }
    }
}