using MAS.Authentications;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MAS.Web.App_Start
{
    public static class StrongTypeSession
    {
        private const string StrongTypeSessionKeyword = "StrongTypeSession";
        private const string ModuleCode = "SchMS";

        public static string UserLoginId
        {
            get
            {
                var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
                return string.Empty; //data != null ? data.UserLoginId : string.Empty;
            }
        }

        public static string UserPassword
        {
            get
            {
                var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
                return string.Empty;  //data != null ? data.UserPassword : string.Empty;
            }
        }

        public static int? UserAutoGeneratedId
        {
            get
            {
                var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
                return 1;
                //return data != null ? (int?)data.UserID : null;
            }
        }

        public static string UserFullName
        {
            get
            {
                var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
                return data != null ? data.UserFullName : string.Empty;
            }
        }

        //public static string UserRole
        //{
        //    get
        //    {
        //        var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
        //        return data != null ? data.GetRole(ModuleCode).Name : string.Empty;
        //    }
        //}

        //public static int? UserRoleAutoGeneratedId
        //{
        //    get
        //    {
        //        var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
        //        return data != null ? data.GetRole(ModuleCode).ID : -1;
        //    }
        //}

        //public static int? UserApplicationAutoGeneratedId
        //{
        //    get
        //    {
        //        var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
        //        return data != null ? (int?)data.Modules.First(x => x.ShortName == "SchMS").ID : null;
        //    }
        //}

        //public static int? UserCompanyID
        //{
        //    get
        //    {
        //        var data = (HttpContext.Current.Items[StrongTypeSessionKeyword] as IUserInfo);
        //        return data != null ? (int?)data.Companies.First().ID : null;
        //    }
        //}

        public static long? GetDefaultBranch
        {
            get
            {
                return (long?)HttpContext.Current.Session["DefaultBranch"];
            }
            set
            {
                HttpContext.Current.Session["DefaultBranch"] = value;
            }
        }

        public static long? GetDefaultCompany
        {
            get
            {
                return (long?)HttpContext.Current.Session["DefaultCompany"];
            }
            set
            {
                HttpContext.Current.Session["DefaultCompany"] = value;
            }
        }
    }
}